/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIHello */

#ifndef _Included_JNIHello
#define _Included_JNIHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIHello
 * Method:    main
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIHello_main
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
